src/Entity/Company.php
<?php

namespace App\Entity;

use App\Repository\CompanyRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=CompanyRepository::class)
 */
class Company
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * @Groups({"company"})
     */
    private $id;

    /**
     * @ORM\Column(type="bigint", unique=true)
     * @Assert\Regex(pattern="/^[0-9]{10}$/", message="NIP ma 10 cyfr")
     * @Assert\NotBlank(message="Uzupełnij pole")
     * @Groups({"company"})
     */
    private $nip;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Uzupełnij pole")
     * @Groups({"company"})
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=180, nullable=true)
     * @Groups({"company"})
     */
    private $street;

    /**
     * @ORM\Column(type="string", length=20)
     * @Assert\NotBlank(message="Uzupełnij pole")
     * @Groups({"company"})
     */
    private $house_nr;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     * @Groups({"company"})
     */
    private $flat_nr;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\NotBlank(message="Uzupełnij pole")
     * @Assert\Regex(pattern="/^[0-9]{2}-[0-9]{3}$/",message="Format kodu xx-xxx")
     * @Groups({"company"})
     */
    private $postcode;

    /**
     * @ORM\Column(type="string", length=180, nullable=true)
     * @Groups({"company"})
     */
    private $place;

    /**
     * @ORM\Column(type="string", length=25)
     * @Assert\NotBlank(message="Uzupełnij pole")
     * @Assert\Regex(pattern="/^[0-9]{9}$/",message="Numer ma 9 cyfr")
     * @Groups({"company"})
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=180)
     * @Assert\Email(message="To nie jest prawidłowy email")
     * @Assert\NotBlank(message="Uzupełnij pole")
     * @Groups({"company"})
     */
    private $email;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="companies", cascade={"persist"})
     * @ORM\JoinColumn(nullable=false)
     */
    private $created_by;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNip(): ?string
    {
        return $this->nip;
    }

    public function setNip(string $nip): self
    {
        $this->nip = $nip;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getStreet(): ?string
    {
        return $this->street;
    }

    public function setStreet(?string $street): self
    {
        $this->street = $street;

        return $this;
    }

    public function getHouseNr(): ?string
    {
        return $this->house_nr;
    }

    public function setHouseNr(string $house_nr): self
    {
        $this->house_nr = $house_nr;

        return $this;
    }

    public function getFlatNr(): ?string
    {
        return $this->flat_nr;
    }

    public function setFlatNr(?string $flat_nr): self
    {
        $this->flat_nr = $flat_nr;

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(string $postcode): self
    {
        $this->postcode = $postcode;

        return $this;
    }
    

    public function getPlace(): ?string
    {
        return $this->place;
    }

    public function setPlace(?string $place): self
    {
        $this->place = $place;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): self
    {
        $this->created_by = $created_by;

        return $this;
    }
}

src/Form/CompanyType.php
<?php

namespace App\Form;

use App\Entity\Company;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nip')
            ->add('name')
            ->add('street')
            ->add('house_nr')
            ->add('flat_nr')
            ->add('postcode')
            ->add('place')
            ->add('phone')
            ->add('email')
            // ->add('created_by', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Company::class,
            'attr' => [
                'novalidate' => 'novalidate',
            ],
        ]);
    }
}

src/Controller/CompanyController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Company;
use App\Entity\User;
use App\Form\CompanyType;
use App\Form\UserType;
use Doctrine\ORM\EntityManagerInterface;
use App\Repository\UserRepository;
use Symfony\Component\Serializer\SerializerInterface;
use Symfony\Component\Serializer\Encoder\JsonEncoder;

/**
 * @Route("/company")
 */
class CompanyController extends AbstractController
{
    /**
     * @Route("/",name="company_index",methods={"GET"})
     */
    public function index(SerializerInterface $serializer): Response
    {
        $companies = $this->getDoctrine()->getRepository(Company::class)->findAllCreatedByUsers();

        $json = $serializer->serialize(
            $companies, 
            'json', 
            ['groups'=>['company', 'user']]
        );
        
        //json response for REST API
        $response = new Response($json);
        $response->headers->set('Content-Type', 'application/json');

        return $response;


        //----------------------------------------------
        //$companies = $this->getDoctrine()->getRepository(Company::class)->findAll();
        // render in twig for testing
        // return $this->render('company/index.html.twig', [
        //     'companies' => $companies,
        // ]);
        //----------------------------------------------
    }


    /**
     * @Route("/new",name="company_new",methods={"GET", "POST"})
     */

    public function new(Request $request, EntityManagerInterface $em): Response
    {
        

        $user = new User();
        $company = new Company;
        $user->addCompany($company);



        $form=$this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {

            $user = $form->getData();
            
            //check user in database
            $savedUser = $em->getRepository(User::class)->findOneBy(['email' => $user->getEmail()]);

            //check companies in database and remove if any
            $companies = $user->getCompanies();

            $savedCompany=null;
            foreach($companies as $row)
            {
                $savedCompany = $em->getRepository(Company::class)->findOneBy(['nip' => $row->getNip()]);
                $savedCompany && $user->removeCompany($row);
                $this->addFlash(
                    'notice-already-saved',
                    'Firma o numerze NIP '. $row->getNip() . ' już istnieje w bazie'
                );
            }
            
            if($savedUser)
            {
                $userCompanies = $user->getCompanies();

                foreach($userCompanies as $userCompany)
                {
                    $user->removeCompany($userCompany);
                    $savedUser->addCompany($userCompany);
                }                
                $em->persist($savedUser);
            } else
            {
                $em->persist($user);
            }

            $em->flush();

            if(!$savedCompany){
                
            return $this->redirectToRoute('company_new');
            }
        }


        return $this->render('company/new.html.twig', [
            'form'=>$form->createView(),
        ]
        );
    }
}

templates/company/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Companies{% endblock %}

{% block body %}

<div class="row justify-content-center mx-auto">

    <div class="col-12 table-responsive tableFixHead" style="max-width: 90vw">

         <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">NIP</th>
              <th scope="col">Nazwa</th>
              <th scope="col">Ulica</th>
              <th scope="col">Numer domu</th>
              <th scope="col">Numer lokalu</th>
              <th scope="col">Kod pocztowy</th>
              <th scope="col">Miejscowość</th>
              <th scope="col">Telefon</th>
              <th scope="col">Email</th>
              <th scope="col">Kto dodał</th>

            </tr>
          </thead>
          <tbody>
            {% for company in companies%}
            <tr>
              <th scope="row">{{company.id}}</th>
              <td>{{company.nip}}</td>
              <td>{{company.name}}}}</td>
              <td>{{company.street}}</td>
              <td>{{company.houseNr}}</td>
              <td>{{company.flatNr}}</td>
              <td>{{company.postcode}}</td>
              <td>{{company.place}}</td>
              <td>{{company.phone}}</td>
              <td>{{company.email}}</td>
              <td>{{company.createdBy.email}}</td>
            </tr>
            
            {% endfor %}
          </tbody>
        </table>
    </div>
</div>

{% endblock %}

templates/company/new.html.twig
{% extends "base.html.twig" %}


{% block body %}

    {% for message in app.flashes('notice-already-saved') %}
      <div class="alert alert-danger">
        {{ message }}
      </div>
    {% endfor %}

    {{ form_start(form, {'attr':{
      'class': 'w-75 justify-content-center container my-5'
    }}) }}
      <p class="h4 text-center mt-3">Zgłoś firmę</p>

      <p class="h6">Twoje dane:</p>

      <div class="row g-3 ">
      <div class="col-md-12">
        {{form_row(form.email)}}
        {{ form_row(form.pesel)}}
        {{ form_row(form.firstname)}}
        {{ form_row(form.lastname)}}
      </div>
        <div class="col-md-12 mt-3">
        <p class="h6">Dane firmy</p>
        </div>
        <ol class="col-md-12 mt-2 companies"
        data-index="{{ form.companies|length > 0 ? form.companies|last.vars.name + 1 : 0 }}"
        data-prototype="{{ form_widget(form.companies.vars.prototype)|e('html_attr') }}">
          {% for company in form.companies %}
              <li class="mt-3">
              {{ form_label(company)}}
              {{ form_widget(company)}}
              </li>
          {% endfor %}
        </ol>
      </div>
      <div class="text-center">
      <button type="button" class="add_item_link btn-sm btn-success" data-collection-holder-class="companies">Dodaj kolejną</button>
      </div>

      <div class="mt-5 text-center">
        {{ form_label(form.submit)}}
        {{
          form_widget(form.submit)
        }}
      </div>



    {{ form_end(form) }}  

{% endblock %}

{% block customjavascripts %}
<script>

const addTagFormDeleteLink = (item) => {
    const removeFormButton = document.createElement('button');
    removeFormButton.innerText = 'Usuń';
    removeFormButton.classList.add("btn-sm")
    removeFormButton.classList.add("btn-danger")

    item.append(removeFormButton);

    removeFormButton.addEventListener('click', (e) => {
        e.preventDefault();
        item.remove();
    });
}

const addFormToCollection = (e) => {
  const collectionHolder = document.querySelector('.' + e.currentTarget.dataset.collectionHolderClass);

  const item = document.createElement('li');

  item.innerHTML = collectionHolder
    .dataset
    .prototype
    .replace(
      /__name__/g,
      collectionHolder.dataset.index
    );

  collectionHolder.appendChild(item);

  collectionHolder.dataset.index++;

   addTagFormDeleteLink(item);
};

document
  .querySelectorAll('.add_item_link')
  .forEach(btn => {
      btn.addEventListener("click", addFormToCollection)
  });

document
    .querySelectorAll('ul.tags li')
    .forEach((tag) => {
        addTagFormDeleteLink(tag)
    })



</script>



{% endblock %}